FROM ubuntu:jammy

RUN apt-get update -y \
  && apt-get install -y \ 
    libstdc++6 \
    openssl\
    libncurses5 \ 
    locales \
  && apt-get clean \
  && rm -f /var/lib/apt/lists/*_*

# Set the locale=9[[[90IOP]O]].UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

