name: Build and test

on: 
  push: 
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/chyzwar/city_trees_buildpack:1.0.6
    
    steps:
    - uses: actions/checkout@v3
  
    - name: Mix install
      shell: bash -l {0} 
      run: mix deps.get

    - name: Compile Deps
      shell: bash -l {0}
      run: mix deps.compile