name: Build and Deploy to Prod

on:
  release:
    types: [published]

env:
  MIX_ENV: prod
  NODE_ENV: production
  SERVER_IP: 195.201.250.214
  SERVER_PORT: 2211
  SERVER_USER: devops
  BUILD_DIR: .build/

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/city-trees/city_trees_buildpack:latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Yarn install
      shell: bash -l {0}
      run: yarn install

    - name: Mix install
      shell: bash -l {0}
      run: mix deps.get --only prod

    - name: Compile Deps
      shell: bash -l {0}
      run: mix deps.compile

    - name: Build static assets
      shell: bash -l {0}
      working-directory: ./apps/city_trees_web
      run: mix assets.deploy

    - name: Build Release
      shell: bash -l {0}
      run: mix release

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ secrets.SSH_KEY_PROD }} 
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS_PROD }}   
        config: |
          Host server
            HostName ${{ env.SERVER_IP }}
            Port ${{ env.SERVER_PORT }}
            User ${{ env.SERVER_USER }}

    - name: Set build path
      run: echo "DEPLOY_PATH=/city_trees/$(date -I)_$GITHUB_SHA" >> $GITHUB_ENV

    - name: Upload new release to server
      shell: bash -l {0}
      run: >-
        rsync 
        -azr
        --mkpath
        --delete
        $BUILD_DIR ${SERVER_USER}@server:${DEPLOY_PATH}

    - name: Update current release
      run: |
        ssh $SERVER_USER@server "
          ln -sfn ${DEPLOY_PATH} /city_trees/current

          cat /dev/null > /city_trees/current/.env
          echo 'PORT=2096' >> /city_trees/current/.env
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}' >>  /city_trees/current/.env
          echo 'SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE_PROD }}' >> /city_trees/current/.env
        "

    - name: Restart service
      run: |
        ssh $SERVER_USER@server sudo systemctl restart city-trees.service
        ssh $SERVER_USER@server /city_trees/current/prod/rel/server/bin/server "CityTreesWeb.Release.migrate"
        ssh $SERVER_USER@server ls -dt /city_trees/* | tail -n +11 | xargs rm -rf

