name: Build and Deploy to Prod

on:
  release:
    types: [published]

env:
  MIX_ENV: prod
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/city-trees/city_trees_buildpack:latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Mix install
      shell: bash -l {0}
      run: mix deps.get --only prod

    - name: Compile Deps
      shell: bash -l {0}
      run: mix deps.compile

    - name: Build static assets
      shell: bash -l {0}
      working-directory: ./apps/city_trees_web
      run: mix assets.deploy

    - name: Build Release
      shell: bash -l {0}
      run: mix release
