name: Build and Deploy Prod

on: 
  push: 
    branches:
      - master

env:
  MIX_ENV: prod
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/city-trees/city_trees_buildpack:latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Mix install
      shell: bash -l {0}
      run: mix deps.get

    - name: Compile Deps
      shell: bash -l {0}
      run: mix deps.compile
